# This is main config file build upon default,
# see https://detekt.dev/docs/introduction/configurations.
# It contains only necessary options.

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
    excludes: [ '**/theme/**', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]


naming:
  # Ignore Composable functions naming, e.g. PascalCase,
  # see https://detekt.dev/docs/introduction/compose/#functionnaming-for-compose
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

style:
  # Ignore magic numbers for Compose, e.g. Color(0xFFEA6D7E),
  # see https://detekt.dev/docs/introduction/compose/#magicnumber-for-compose
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotated: [ 'Composable' ]
  # Ignore private preview for Compose,
  # see https://detekt.dev/docs/introduction/compose/#unusedprivatemember-for-compose
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  ForbiddenComment:
    allowedPatterns: 'TODO:'

complexity:
  LongParameterList:
    ignoreAnnotated: [ 'Composable' ]
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]

# Set active to false because it clashes with MaxLineLength
# see https://detekt.dev/docs/next/rules/formatting/#maximumlinelength
formatting:
  MaximumLineLength:
    active: false