"""create initial tables

Revision ID: 340329d5ad5d
Revises: 
Create Date: 2025-06-06 09:01:58.005397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '340329d5ad5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('tickets',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flight_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('departure_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('adults', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('children', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hotel_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_price', mysql.FLOAT(), nullable=True),
    sa.Column('flight_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('pendiente', 'aceptada', 'rechazada'), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('flight_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('flight_price', mysql.FLOAT(), nullable=True),
    sa.Column('hotel_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_price', mysql.FLOAT(), nullable=True),
    sa.Column('hotel_nights', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_model', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_price', mysql.FLOAT(), nullable=True),
    sa.Column('vehicle_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', mysql.FLOAT(), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###
