"""mensaje

Revision ID: e7ecc629dd35
Revises: 046b8b6216dc
Create Date: 2025-06-06 09:42:31.635955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ecc629dd35'
down_revision: Union[str, None] = '046b8b6216dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('flight_id', sa.String(length=255), nullable=True),
    sa.Column('hotel_id', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('hotel_limit', sa.Integer(), nullable=True),
    sa.Column('vehicle_limit', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('flight_id', sa.String(length=255), nullable=True),
    sa.Column('hotel_id', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.String(length=255), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'aceptada', 'rechazada', name='tripstatusenum'), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('flight_name', sa.String(length=255), nullable=True),
    sa.Column('flight_price', sa.Float(), nullable=True),
    sa.Column('hotel_name', sa.String(length=255), nullable=True),
    sa.Column('hotel_price', sa.Float(), nullable=True),
    sa.Column('hotel_nights', sa.Integer(), nullable=True),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('vehicle_price', sa.Float(), nullable=True),
    sa.Column('vehicle_days', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
